{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU utilisation on VMs",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"swmando-1:9100|swmando-2:9100\"}[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory consumption on VMs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"swmando-1:9100|swmando-2:9100\"} - node_memory_MemAvailable_bytes{instance=~\"swmando-1:9100|swmando-2:9100\"}) / node_memory_MemTotal_bytes{instance=~\"swmando-1:9100|swmando-2:9100\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "DNS queries per minute",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{job=\"bind\", type=\"A\", view=\"_default\"}[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InfluxDB Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MySQL selects per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 5 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{job=\"mysql\",command=\"select\"}[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total{job=\"nginx\"}[1m])*60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HAproxy Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HAproxy 1 Docker Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-1:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Keepalived VRRP State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Item counts for all discovered Agamas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT LAST(items) FROM \"agama-stats\" GROUP BY \"name\""
    }
   ]
  },
  {
   "title": "Current number of items in my Agama",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT LAST(*) FROM \"agama-stats\" WHERE \"name\" = 'swmando-1.itqurd.az.'"
    }
   ]
  },
  {
   "title": "HAproxy 2 Docker Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"lb-2:9101\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}