- name: Restart Mysql
  service:
    name: mysql
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ replication_user_mysql }}"
    primary_password: "{{ replication_password_mysql }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname != mysql_host
  no_log: true

- name: Restart prometheus-mysqld-exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted

- name: Restart cron
  service:
    name: cron
    state: restarted

- name: Reload rndc
  command: rndc reload

